/**
 * PRS-99: map OpenSubtitles tokenizer junk → real English forms.
 * Targets are lowercase to match FrequencyWords orthography.
 */

export const EN_JUNK_REPLACEMENTS: Readonly<Record<string, string>> = {
  wasn: "wasn't",
  isn: "isn't",
  aren: "aren't",
  don: "don't",
  doesn: "doesn't",
  didn: "didn't",
  couldn: "couldn't",
  shouldn: "shouldn't",
  wouldn: "wouldn't",
  hasn: "hasn't",
  hadn: "hadn't",
  weren: "weren't",
  mustn: "mustn't",
  haven: "haven't",
  won: "won't",
  ain: "ain't",
  "'m": "i'm",
  "'ll": "i'll",
  "'ve": "i've",
  "'d": "i'd",
  "'re": "you're",
  "'clock": "o'clock",
  "'mon": "c'mon",
  "'all": "y'all",
  // Prefer "because"; if it already exists, soft-deactivate "'cause" instead.
  "'cause": "because",
};

/** Offline glosses for replacement targets (ESL-friendly). */
export const EN_REPLACEMENT_GLOSSES: Readonly<
  Record<string, { translation: string; example_sentence: string }>
> = {
  "wasn't": {
    translation: "was not",
    example_sentence: "He wasn't ready for the test.",
  },
  "isn't": {
    translation: "is not",
    example_sentence: "This isn't the right answer.",
  },
  "aren't": {
    translation: "are not",
    example_sentence: "They aren't coming to dinner tonight.",
  },
  "don't": {
    translation: "do not",
    example_sentence: "I don't understand this word yet.",
  },
  "doesn't": {
    translation: "does not",
    example_sentence: "She doesn't like cold coffee.",
  },
  "didn't": {
    translation: "did not",
    example_sentence: "We didn't finish the homework.",
  },
  "couldn't": {
    translation: "could not",
    example_sentence: "I couldn't hear the speaker clearly.",
  },
  "shouldn't": {
    translation: "should not",
    example_sentence: "You shouldn't skip breakfast every day.",
  },
  "wouldn't": {
    translation: "would not",
    example_sentence: "He wouldn't share his notes with us.",
  },
  "hasn't": {
    translation: "has not",
    example_sentence: "She hasn't called me back yet.",
  },
  "hadn't": {
    translation: "had not",
    example_sentence: "I hadn't seen that movie before.",
  },
  "weren't": {
    translation: "were not",
    example_sentence: "They weren't at the station on time.",
  },
  "mustn't": {
    translation: "must not",
    example_sentence: "You mustn't open the door yet.",
  },
  "haven't": {
    translation: "have not",
    example_sentence: "I haven't tried that restaurant.",
  },
  "won't": {
    translation: "will not",
    example_sentence: "It won't rain this afternoon.",
  },
  "ain't": {
    translation: "is/are/am not (informal)",
    example_sentence: "That ain't the way we say it here.",
  },
  "i'm": {
    translation: "I am",
    example_sentence: "I'm learning English every day.",
  },
  "i'll": {
    translation: "I will",
    example_sentence: "I'll call you after class.",
  },
  "i've": {
    translation: "I have",
    example_sentence: "I've finished the first lesson.",
  },
  "i'd": {
    translation: "I would / I had",
    example_sentence: "I'd like another example, please.",
  },
  "you're": {
    translation: "you are",
    example_sentence: "You're doing great with pronunciation.",
  },
  "o'clock": {
    translation: "exactly on the hour",
    example_sentence: "The meeting starts at three o'clock.",
  },
  "c'mon": {
    translation: "come on (informal)",
    example_sentence: "C'mon, let's practice one more time.",
  },
  "y'all": {
    translation: "you all (informal)",
    example_sentence: "Y'all did well on today's quiz.",
  },
  because: {
    translation: "for the reason that",
    example_sentence: "I stayed home because I felt sick.",
  },
};

/** Tokens with no honest 1:1 teachable form — soft-deactivate in DB. */
export const EN_UNMAPPABLE_JUNK: ReadonlySet<string> = new Set([
  "'s",
  "'t",
  "'ii",
  "'you",
  "'i",
  "'the",
  "'and",
  "'s-",
  "'t-",
  "'am",
  "'cause",
  "lt",
  "dr",
  "mr",
  "ms",
  "st",
  "pm",
  "tv",
  "mrs",
  "mrs.",
  "mr.",
  "dr.",
  "ms.",
  "st.",
  "al",
  "ed",
  "bo",
  "jo",
  "di",
  "li",
  "de",
  "el",
  "le",
  "si",
  "mi",
  "la",
  "ll",
  "uh",
  "um",
  "huh",
  "ow",
  "oi",
  "aw",
  "mm-hmm",
  "uh-huh",
  "hmm",
  "ah",
  "eh",
  "er",
]);

/** Backfill words appended after removing unmappable junk (PRS-99). */
export const EN_BACKFILL_WORDS: readonly string[] = [
  "genuine",
  "judging",
  "doubts",
  "ceiling",
  "practicing",
  "somewhat",
  "established",
  "attempted",
  "generations",
  "gathering",
  "electrical",
  "couples",
  "depend",
  "institute",
  "principle",
  "fixing",
  "therapist",
  "compete",
  "compliment",
  "worship",
  "residence",
  "democracy",
  "published",
  "myth",
  "helpless",
  "execution",
  "appetite",
  "formal",
  "strictly",
  "chickens",
  "technical",
  "meets",
  "brutal",
  "vain",
  "switched",
  "deer",
  "dresses",
  "retire",
  "overcome",
  "inspiration",
  "thrilled",
  "suggestion",
  "sailor",
  "destination",
  "picnic",
  "trucks",
  "rank",
  "blocked",
  "strict",
  "formula",
  "clerk",
  "disturbed",
  "cafe",
  "wandering",
  "consciousness",
  "bare",
  "butcher",
  "arrangement",
  "chased",
  "ministry",
  "sweater",
  "locate",
  "apologise",
  "examine",
  "trains",
  "candle",
  "prior",
  "stream",
  "passage",
  "reaching",
  "organ",
  "directions",
  "outer",
  "proves",
  "luxury",
  "funds",
  "sunset",
  "strings",
  "fortunately",
  "gotcha",
  "tomb",
  "horizon",
  "engineering",
  "element",
  "balloon",
];
